spring:
  application:
    name: product-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: productservices

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0