spring:
  application:
    name: product-service

  data:
    mongodb:
      host: localhost
      port: 27017
      database: productservices

  zipkin:
    baseurl: http://localthost:9411

management:
  tracing:
    sampling:
      probability: 1
  zipkin:
    tracing:
      enabled: true


eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka

server:
  port: 0